Repository adaptlearning/adapt-contrib-pageLevelProgress, pull requests merged in 2024-05, with the labels that each got.

#216 New: add model type selector to drawer item button (fixes #185)
  templates/pageLevelProgressItem.jsx
Labels: enhancement

#218 Fix: Added transparent inner border and larger minimum
  less/pageLevelProgressIndicator.less
Labels: bug

#219 Fix: Clarify _showPageCompletion functionality (fixes #215)
  README.md
  properties.schema
  schema/contentobject.schema.json
  schema/course.schema.json
Labels: documentation

#221 New: Added progressive ItemsComponentModel bars
  js/PageLevelProgressIndicatorView.js
  js/adapt-contrib-pageLevelProgress.js
Labels: enhancement
