Repository adaptlearning/adapt-contrib-pageLevelProgress, pull requests merged in 2025-03, with the labels that each got.

#244 Chore: Add support for new issue experience (fixes #241)
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: bug

#246 Fix: Added event trigger (fixes; #245)
  js/PageLevelProgressNavigationView.js
Labels: enhancement

#243 Update: added migration scripts (fixes #242
  migrations/v2.js
  migrations/v3.js
  migrations/v4.js
  migrations/v5.js
  migrations/v6.js
  migrations/v7.js
Labels: enhancement, ready to release
